package com.hy.service.dto;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class SvcServiceItemDTO implements Serializable {
    /**
     * 服务项目id
     * serviceItemId
     * service_item_id
     */
    private Integer serviceItemId;

    /**
     * 服务品类id
     * serviceClassId
     * service_class_id
     */
    private Integer serviceClassId;

    /**
     * 服务大类id
     * bigClassId
     * big_class_id
     */
    private Integer bigClassId;

    /**
     * 服务项目名称
     * serviceItemName
     * service_item_name
     */
    private String serviceItemName;

    /**
     * 基础数据版本(1-旧版本，2-新版本)
     * baseDataVersion
     * base_data_version
     */
    private Integer baseDataVersion;

    /**
     * 质保期（天）
     * qualityGuarantee
     * quality_guarantee
     */
    private Integer qualityGuarantee;

    /**
     * 收费单位
     * chargeUnit
     * charge_unit
     */
    private String chargeUnit;

    /**
     * 创建人
     * createUser
     * create_user
     */
    private Integer createUser;

    /**
     * 创建时间
     * createTime
     * create_time
     */
    private Date createTime;

    /**
     * 更新人
     * updateUser
     * update_user
     */
    private Integer updateUser;

    /**
     * 更新时间
     * updateTime
     * update_time
     */
    private Date updateTime;

    /**
     * 禁用flag
     * offFlag
     * off_flag
     */
    private Integer offFlag;

    /**
     * 是否商城项目 0:否 1:是
     * ismallFlag
     * ismall_flag
     */
    private Integer ismallFlag;

    /**
     * 数据创建时间
     * screateTime
     * screate_time
     */
    private Date screateTime;

    /**
     * 数据更新时间
     * supdateTime
     * supdate_time
     */
    private Date supdateTime;

    /**
     * 1:删除 0:未删除
     * delFlag
     * del_flag
     */
    private Integer delFlag;

    /**
     * 是否需要拍照（0-否 1-是）
     * needPhotoFlag
     * need_photo_flag
     */
    private Integer needPhotoFlag;

    /**
     * 是否需要填写故障原因、处理结果（0-否 1-是）
     * needReasonResultFlag
     * need_reason_result_flag
     */
    private Integer needReasonResultFlag;

    /**
     * 下单最大项目数
     * orderMaxItemNum
     * order_max_item_num
     */
    private Integer orderMaxItemNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table svc_service_item
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
}
