package com.hy.repository.mapper;

import com.hy.repository.po.MaterialInfoPO;
import com.hy.repository.po.MaterialInfoPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MaterialInfoPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_info
     *
     * @mbg.generated
     */
    long countByExample(MaterialInfoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_info
     *
     * @mbg.generated
     */
    int deleteByExample(MaterialInfoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer materialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_info
     *
     * @mbg.generated
     */
    int insert(MaterialInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_info
     *
     * @mbg.generated
     */
    int insertSelective(MaterialInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_info
     *
     * @mbg.generated
     */
    List<MaterialInfoPO> selectByExample(MaterialInfoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_info
     *
     * @mbg.generated
     */
    MaterialInfoPO selectByPrimaryKey(Integer materialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MaterialInfoPO record, @Param("example") MaterialInfoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MaterialInfoPO record, @Param("example") MaterialInfoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MaterialInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MaterialInfoPO record);
}