package com.hy.repository.po;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Created by wyx on 2018-05-02.
 * 
 * @author wyx
 * @title material_info
 * @date 2018-05-02
 */
@Data
@NoArgsConstructor
public class MaterialInfoPO implements Serializable {
    /**
     * 物料ID
     * materialId 
     * material_id
     */
    private Integer materialId;

    /**
     * 服务大类ID
     * bigClassId 
     * big_class_id
     */
    private Integer bigClassId;

    /**
     * 物料分类
     * materialClass 
     * material_class
     */
    private Integer materialClass;

    /**
     * 物料名称
     * materialName 
     * material_name
     */
    private String materialName;

    /**
     * 物料号
     * materialNo 
     * material_no
     */
    private String materialNo;

    /**
     * 销售价格
     * salePrice 
     * sale_price
     */
    private BigDecimal salePrice;

    /**
     * 业务模式（0公服用料；1自营入库；2门店取货；3直发代销；4直发平台）
     * bizMode 
     * biz_mode
     */
    private Integer bizMode;

    /**
     * 是否可关联设备
     * relatedEquipFlag 
     * related_equip_flag
     */
    private Integer relatedEquipFlag;

    /**
     * 原系统物料编码
     * originalSystemMaterialNo 
     * original_system_material_no
     */
    private String originalSystemMaterialNo;

    /**
     * 删除FLAG
     * deleteFlag 
     * delete_flag
     */
    private Integer deleteFlag;

    /**
     * 物料类型(财务使用：1-能源 2-物资 3-计量 4-服务物料)
     * materialType 
     * material_type
     */
    private Integer materialType;

    /**
     * 计量单位
     * measureUnit 
     * measure_unit
     */
    private String measureUnit;

    /**
     * 采购价格
     * purchasePrice 
     * purchase_price
     */
    private BigDecimal purchasePrice;

    /**
     * 厂家保修期(天数)
     * venderGuarantee 
     * vender_guarantee
     */
    private Integer venderGuarantee;

    /**
     * 平台保修期(天数)
     * platformGuarantee 
     * platform_guarantee
     */
    private Integer platformGuarantee;

    /**
     * 操作单位
     * operatorComp 
     * operator_comp
     */
    private String operatorComp;

    /**
     * 创建用户
     * createUser 
     * create_user
     */
    private Integer createUser;

    /**
     * 创建时间
     * createTime 
     * create_time
     */
    private Date createTime;

    /**
     * 更新用户
     * updateUser 
     * update_user
     */
    private Integer updateUser;

    /**
     * 更新时间
     * updateTime 
     * update_time
     */
    private Date updateTime;

    /**
     * 维保渠道商ID
     * maintenanceChannelId 
     * maintenance_channel_id
     */
    private Integer maintenanceChannelId;

    /**
     * 0 -不可售;1-可售
     * sellFlag 
     * sell_flag
     */
    private Integer sellFlag;

    /**
     * 品牌表id
     * brandId 
     * brand_id
     */
    private Integer brandId;

    /**
     * 商品SPUID
     * spuGoodsId 
     * spu_goods_id
     */
    private Integer spuGoodsId;

    /**
     * 物料商城销售标识（0未在商城；1已在商城）
     * omtFlag 
     * omt_flag
     */
    private Integer omtFlag;

    /**
     * 特殊物料标记（0-普通物料  1-燃气表）
     * specialMaterialFlag 
     * special_material_flag
     */
    private Integer specialMaterialFlag;

    /**
     * 数据创建时间
     * screateTime 
     * screate_time
     */
    private Date screateTime;

    /**
     * 数据更新时间
     * supdateTime 
     * supdate_time
     */
    private Date supdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table material_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}