package com.hy.repository.po;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MaterialInfoPOExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table material_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table material_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table material_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table material_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_info
     *
     * @mbg.generated
     */
    public MaterialInfoPOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table material_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMaterialIdIsNull() {
            addCriterion("material_id is null");
            return (Criteria) this;
        }

        public Criteria andMaterialIdIsNotNull() {
            addCriterion("material_id is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialIdEqualTo(Integer value) {
            addCriterion("material_id =", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdNotEqualTo(Integer value) {
            addCriterion("material_id <>", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdGreaterThan(Integer value) {
            addCriterion("material_id >", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("material_id >=", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdLessThan(Integer value) {
            addCriterion("material_id <", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdLessThanOrEqualTo(Integer value) {
            addCriterion("material_id <=", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdIn(List<Integer> values) {
            addCriterion("material_id in", values, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdNotIn(List<Integer> values) {
            addCriterion("material_id not in", values, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdBetween(Integer value1, Integer value2) {
            addCriterion("material_id between", value1, value2, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdNotBetween(Integer value1, Integer value2) {
            addCriterion("material_id not between", value1, value2, "materialId");
            return (Criteria) this;
        }

        public Criteria andBigClassIdIsNull() {
            addCriterion("big_class_id is null");
            return (Criteria) this;
        }

        public Criteria andBigClassIdIsNotNull() {
            addCriterion("big_class_id is not null");
            return (Criteria) this;
        }

        public Criteria andBigClassIdEqualTo(Integer value) {
            addCriterion("big_class_id =", value, "bigClassId");
            return (Criteria) this;
        }

        public Criteria andBigClassIdNotEqualTo(Integer value) {
            addCriterion("big_class_id <>", value, "bigClassId");
            return (Criteria) this;
        }

        public Criteria andBigClassIdGreaterThan(Integer value) {
            addCriterion("big_class_id >", value, "bigClassId");
            return (Criteria) this;
        }

        public Criteria andBigClassIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("big_class_id >=", value, "bigClassId");
            return (Criteria) this;
        }

        public Criteria andBigClassIdLessThan(Integer value) {
            addCriterion("big_class_id <", value, "bigClassId");
            return (Criteria) this;
        }

        public Criteria andBigClassIdLessThanOrEqualTo(Integer value) {
            addCriterion("big_class_id <=", value, "bigClassId");
            return (Criteria) this;
        }

        public Criteria andBigClassIdIn(List<Integer> values) {
            addCriterion("big_class_id in", values, "bigClassId");
            return (Criteria) this;
        }

        public Criteria andBigClassIdNotIn(List<Integer> values) {
            addCriterion("big_class_id not in", values, "bigClassId");
            return (Criteria) this;
        }

        public Criteria andBigClassIdBetween(Integer value1, Integer value2) {
            addCriterion("big_class_id between", value1, value2, "bigClassId");
            return (Criteria) this;
        }

        public Criteria andBigClassIdNotBetween(Integer value1, Integer value2) {
            addCriterion("big_class_id not between", value1, value2, "bigClassId");
            return (Criteria) this;
        }

        public Criteria andMaterialClassIsNull() {
            addCriterion("material_class is null");
            return (Criteria) this;
        }

        public Criteria andMaterialClassIsNotNull() {
            addCriterion("material_class is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialClassEqualTo(Integer value) {
            addCriterion("material_class =", value, "materialClass");
            return (Criteria) this;
        }

        public Criteria andMaterialClassNotEqualTo(Integer value) {
            addCriterion("material_class <>", value, "materialClass");
            return (Criteria) this;
        }

        public Criteria andMaterialClassGreaterThan(Integer value) {
            addCriterion("material_class >", value, "materialClass");
            return (Criteria) this;
        }

        public Criteria andMaterialClassGreaterThanOrEqualTo(Integer value) {
            addCriterion("material_class >=", value, "materialClass");
            return (Criteria) this;
        }

        public Criteria andMaterialClassLessThan(Integer value) {
            addCriterion("material_class <", value, "materialClass");
            return (Criteria) this;
        }

        public Criteria andMaterialClassLessThanOrEqualTo(Integer value) {
            addCriterion("material_class <=", value, "materialClass");
            return (Criteria) this;
        }

        public Criteria andMaterialClassIn(List<Integer> values) {
            addCriterion("material_class in", values, "materialClass");
            return (Criteria) this;
        }

        public Criteria andMaterialClassNotIn(List<Integer> values) {
            addCriterion("material_class not in", values, "materialClass");
            return (Criteria) this;
        }

        public Criteria andMaterialClassBetween(Integer value1, Integer value2) {
            addCriterion("material_class between", value1, value2, "materialClass");
            return (Criteria) this;
        }

        public Criteria andMaterialClassNotBetween(Integer value1, Integer value2) {
            addCriterion("material_class not between", value1, value2, "materialClass");
            return (Criteria) this;
        }

        public Criteria andMaterialNameIsNull() {
            addCriterion("material_name is null");
            return (Criteria) this;
        }

        public Criteria andMaterialNameIsNotNull() {
            addCriterion("material_name is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialNameEqualTo(String value) {
            addCriterion("material_name =", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameNotEqualTo(String value) {
            addCriterion("material_name <>", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameGreaterThan(String value) {
            addCriterion("material_name >", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameGreaterThanOrEqualTo(String value) {
            addCriterion("material_name >=", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameLessThan(String value) {
            addCriterion("material_name <", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameLessThanOrEqualTo(String value) {
            addCriterion("material_name <=", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameLike(String value) {
            addCriterion("material_name like", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameNotLike(String value) {
            addCriterion("material_name not like", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameIn(List<String> values) {
            addCriterion("material_name in", values, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameNotIn(List<String> values) {
            addCriterion("material_name not in", values, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameBetween(String value1, String value2) {
            addCriterion("material_name between", value1, value2, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameNotBetween(String value1, String value2) {
            addCriterion("material_name not between", value1, value2, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNoIsNull() {
            addCriterion("material_no is null");
            return (Criteria) this;
        }

        public Criteria andMaterialNoIsNotNull() {
            addCriterion("material_no is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialNoEqualTo(String value) {
            addCriterion("material_no =", value, "materialNo");
            return (Criteria) this;
        }

        public Criteria andMaterialNoNotEqualTo(String value) {
            addCriterion("material_no <>", value, "materialNo");
            return (Criteria) this;
        }

        public Criteria andMaterialNoGreaterThan(String value) {
            addCriterion("material_no >", value, "materialNo");
            return (Criteria) this;
        }

        public Criteria andMaterialNoGreaterThanOrEqualTo(String value) {
            addCriterion("material_no >=", value, "materialNo");
            return (Criteria) this;
        }

        public Criteria andMaterialNoLessThan(String value) {
            addCriterion("material_no <", value, "materialNo");
            return (Criteria) this;
        }

        public Criteria andMaterialNoLessThanOrEqualTo(String value) {
            addCriterion("material_no <=", value, "materialNo");
            return (Criteria) this;
        }

        public Criteria andMaterialNoLike(String value) {
            addCriterion("material_no like", value, "materialNo");
            return (Criteria) this;
        }

        public Criteria andMaterialNoNotLike(String value) {
            addCriterion("material_no not like", value, "materialNo");
            return (Criteria) this;
        }

        public Criteria andMaterialNoIn(List<String> values) {
            addCriterion("material_no in", values, "materialNo");
            return (Criteria) this;
        }

        public Criteria andMaterialNoNotIn(List<String> values) {
            addCriterion("material_no not in", values, "materialNo");
            return (Criteria) this;
        }

        public Criteria andMaterialNoBetween(String value1, String value2) {
            addCriterion("material_no between", value1, value2, "materialNo");
            return (Criteria) this;
        }

        public Criteria andMaterialNoNotBetween(String value1, String value2) {
            addCriterion("material_no not between", value1, value2, "materialNo");
            return (Criteria) this;
        }

        public Criteria andSalePriceIsNull() {
            addCriterion("sale_price is null");
            return (Criteria) this;
        }

        public Criteria andSalePriceIsNotNull() {
            addCriterion("sale_price is not null");
            return (Criteria) this;
        }

        public Criteria andSalePriceEqualTo(BigDecimal value) {
            addCriterion("sale_price =", value, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceNotEqualTo(BigDecimal value) {
            addCriterion("sale_price <>", value, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceGreaterThan(BigDecimal value) {
            addCriterion("sale_price >", value, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sale_price >=", value, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceLessThan(BigDecimal value) {
            addCriterion("sale_price <", value, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sale_price <=", value, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceIn(List<BigDecimal> values) {
            addCriterion("sale_price in", values, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceNotIn(List<BigDecimal> values) {
            addCriterion("sale_price not in", values, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sale_price between", value1, value2, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sale_price not between", value1, value2, "salePrice");
            return (Criteria) this;
        }

        public Criteria andBizModeIsNull() {
            addCriterion("biz_mode is null");
            return (Criteria) this;
        }

        public Criteria andBizModeIsNotNull() {
            addCriterion("biz_mode is not null");
            return (Criteria) this;
        }

        public Criteria andBizModeEqualTo(Integer value) {
            addCriterion("biz_mode =", value, "bizMode");
            return (Criteria) this;
        }

        public Criteria andBizModeNotEqualTo(Integer value) {
            addCriterion("biz_mode <>", value, "bizMode");
            return (Criteria) this;
        }

        public Criteria andBizModeGreaterThan(Integer value) {
            addCriterion("biz_mode >", value, "bizMode");
            return (Criteria) this;
        }

        public Criteria andBizModeGreaterThanOrEqualTo(Integer value) {
            addCriterion("biz_mode >=", value, "bizMode");
            return (Criteria) this;
        }

        public Criteria andBizModeLessThan(Integer value) {
            addCriterion("biz_mode <", value, "bizMode");
            return (Criteria) this;
        }

        public Criteria andBizModeLessThanOrEqualTo(Integer value) {
            addCriterion("biz_mode <=", value, "bizMode");
            return (Criteria) this;
        }

        public Criteria andBizModeIn(List<Integer> values) {
            addCriterion("biz_mode in", values, "bizMode");
            return (Criteria) this;
        }

        public Criteria andBizModeNotIn(List<Integer> values) {
            addCriterion("biz_mode not in", values, "bizMode");
            return (Criteria) this;
        }

        public Criteria andBizModeBetween(Integer value1, Integer value2) {
            addCriterion("biz_mode between", value1, value2, "bizMode");
            return (Criteria) this;
        }

        public Criteria andBizModeNotBetween(Integer value1, Integer value2) {
            addCriterion("biz_mode not between", value1, value2, "bizMode");
            return (Criteria) this;
        }

        public Criteria andRelatedEquipFlagIsNull() {
            addCriterion("related_equip_flag is null");
            return (Criteria) this;
        }

        public Criteria andRelatedEquipFlagIsNotNull() {
            addCriterion("related_equip_flag is not null");
            return (Criteria) this;
        }

        public Criteria andRelatedEquipFlagEqualTo(Integer value) {
            addCriterion("related_equip_flag =", value, "relatedEquipFlag");
            return (Criteria) this;
        }

        public Criteria andRelatedEquipFlagNotEqualTo(Integer value) {
            addCriterion("related_equip_flag <>", value, "relatedEquipFlag");
            return (Criteria) this;
        }

        public Criteria andRelatedEquipFlagGreaterThan(Integer value) {
            addCriterion("related_equip_flag >", value, "relatedEquipFlag");
            return (Criteria) this;
        }

        public Criteria andRelatedEquipFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("related_equip_flag >=", value, "relatedEquipFlag");
            return (Criteria) this;
        }

        public Criteria andRelatedEquipFlagLessThan(Integer value) {
            addCriterion("related_equip_flag <", value, "relatedEquipFlag");
            return (Criteria) this;
        }

        public Criteria andRelatedEquipFlagLessThanOrEqualTo(Integer value) {
            addCriterion("related_equip_flag <=", value, "relatedEquipFlag");
            return (Criteria) this;
        }

        public Criteria andRelatedEquipFlagIn(List<Integer> values) {
            addCriterion("related_equip_flag in", values, "relatedEquipFlag");
            return (Criteria) this;
        }

        public Criteria andRelatedEquipFlagNotIn(List<Integer> values) {
            addCriterion("related_equip_flag not in", values, "relatedEquipFlag");
            return (Criteria) this;
        }

        public Criteria andRelatedEquipFlagBetween(Integer value1, Integer value2) {
            addCriterion("related_equip_flag between", value1, value2, "relatedEquipFlag");
            return (Criteria) this;
        }

        public Criteria andRelatedEquipFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("related_equip_flag not between", value1, value2, "relatedEquipFlag");
            return (Criteria) this;
        }

        public Criteria andOriginalSystemMaterialNoIsNull() {
            addCriterion("original_system_material_no is null");
            return (Criteria) this;
        }

        public Criteria andOriginalSystemMaterialNoIsNotNull() {
            addCriterion("original_system_material_no is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalSystemMaterialNoEqualTo(String value) {
            addCriterion("original_system_material_no =", value, "originalSystemMaterialNo");
            return (Criteria) this;
        }

        public Criteria andOriginalSystemMaterialNoNotEqualTo(String value) {
            addCriterion("original_system_material_no <>", value, "originalSystemMaterialNo");
            return (Criteria) this;
        }

        public Criteria andOriginalSystemMaterialNoGreaterThan(String value) {
            addCriterion("original_system_material_no >", value, "originalSystemMaterialNo");
            return (Criteria) this;
        }

        public Criteria andOriginalSystemMaterialNoGreaterThanOrEqualTo(String value) {
            addCriterion("original_system_material_no >=", value, "originalSystemMaterialNo");
            return (Criteria) this;
        }

        public Criteria andOriginalSystemMaterialNoLessThan(String value) {
            addCriterion("original_system_material_no <", value, "originalSystemMaterialNo");
            return (Criteria) this;
        }

        public Criteria andOriginalSystemMaterialNoLessThanOrEqualTo(String value) {
            addCriterion("original_system_material_no <=", value, "originalSystemMaterialNo");
            return (Criteria) this;
        }

        public Criteria andOriginalSystemMaterialNoLike(String value) {
            addCriterion("original_system_material_no like", value, "originalSystemMaterialNo");
            return (Criteria) this;
        }

        public Criteria andOriginalSystemMaterialNoNotLike(String value) {
            addCriterion("original_system_material_no not like", value, "originalSystemMaterialNo");
            return (Criteria) this;
        }

        public Criteria andOriginalSystemMaterialNoIn(List<String> values) {
            addCriterion("original_system_material_no in", values, "originalSystemMaterialNo");
            return (Criteria) this;
        }

        public Criteria andOriginalSystemMaterialNoNotIn(List<String> values) {
            addCriterion("original_system_material_no not in", values, "originalSystemMaterialNo");
            return (Criteria) this;
        }

        public Criteria andOriginalSystemMaterialNoBetween(String value1, String value2) {
            addCriterion("original_system_material_no between", value1, value2, "originalSystemMaterialNo");
            return (Criteria) this;
        }

        public Criteria andOriginalSystemMaterialNoNotBetween(String value1, String value2) {
            addCriterion("original_system_material_no not between", value1, value2, "originalSystemMaterialNo");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("delete_flag is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("delete_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(Integer value) {
            addCriterion("delete_flag =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(Integer value) {
            addCriterion("delete_flag <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(Integer value) {
            addCriterion("delete_flag >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("delete_flag >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(Integer value) {
            addCriterion("delete_flag <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(Integer value) {
            addCriterion("delete_flag <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<Integer> values) {
            addCriterion("delete_flag in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<Integer> values) {
            addCriterion("delete_flag not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(Integer value1, Integer value2) {
            addCriterion("delete_flag between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("delete_flag not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeIsNull() {
            addCriterion("material_type is null");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeIsNotNull() {
            addCriterion("material_type is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeEqualTo(Integer value) {
            addCriterion("material_type =", value, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeNotEqualTo(Integer value) {
            addCriterion("material_type <>", value, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeGreaterThan(Integer value) {
            addCriterion("material_type >", value, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("material_type >=", value, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeLessThan(Integer value) {
            addCriterion("material_type <", value, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeLessThanOrEqualTo(Integer value) {
            addCriterion("material_type <=", value, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeIn(List<Integer> values) {
            addCriterion("material_type in", values, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeNotIn(List<Integer> values) {
            addCriterion("material_type not in", values, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeBetween(Integer value1, Integer value2) {
            addCriterion("material_type between", value1, value2, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("material_type not between", value1, value2, "materialType");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitIsNull() {
            addCriterion("measure_unit is null");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitIsNotNull() {
            addCriterion("measure_unit is not null");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitEqualTo(String value) {
            addCriterion("measure_unit =", value, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitNotEqualTo(String value) {
            addCriterion("measure_unit <>", value, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitGreaterThan(String value) {
            addCriterion("measure_unit >", value, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitGreaterThanOrEqualTo(String value) {
            addCriterion("measure_unit >=", value, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitLessThan(String value) {
            addCriterion("measure_unit <", value, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitLessThanOrEqualTo(String value) {
            addCriterion("measure_unit <=", value, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitLike(String value) {
            addCriterion("measure_unit like", value, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitNotLike(String value) {
            addCriterion("measure_unit not like", value, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitIn(List<String> values) {
            addCriterion("measure_unit in", values, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitNotIn(List<String> values) {
            addCriterion("measure_unit not in", values, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitBetween(String value1, String value2) {
            addCriterion("measure_unit between", value1, value2, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andMeasureUnitNotBetween(String value1, String value2) {
            addCriterion("measure_unit not between", value1, value2, "measureUnit");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceIsNull() {
            addCriterion("purchase_price is null");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceIsNotNull() {
            addCriterion("purchase_price is not null");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceEqualTo(BigDecimal value) {
            addCriterion("purchase_price =", value, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceNotEqualTo(BigDecimal value) {
            addCriterion("purchase_price <>", value, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceGreaterThan(BigDecimal value) {
            addCriterion("purchase_price >", value, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("purchase_price >=", value, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceLessThan(BigDecimal value) {
            addCriterion("purchase_price <", value, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("purchase_price <=", value, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceIn(List<BigDecimal> values) {
            addCriterion("purchase_price in", values, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceNotIn(List<BigDecimal> values) {
            addCriterion("purchase_price not in", values, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("purchase_price between", value1, value2, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasePriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("purchase_price not between", value1, value2, "purchasePrice");
            return (Criteria) this;
        }

        public Criteria andVenderGuaranteeIsNull() {
            addCriterion("vender_guarantee is null");
            return (Criteria) this;
        }

        public Criteria andVenderGuaranteeIsNotNull() {
            addCriterion("vender_guarantee is not null");
            return (Criteria) this;
        }

        public Criteria andVenderGuaranteeEqualTo(Integer value) {
            addCriterion("vender_guarantee =", value, "venderGuarantee");
            return (Criteria) this;
        }

        public Criteria andVenderGuaranteeNotEqualTo(Integer value) {
            addCriterion("vender_guarantee <>", value, "venderGuarantee");
            return (Criteria) this;
        }

        public Criteria andVenderGuaranteeGreaterThan(Integer value) {
            addCriterion("vender_guarantee >", value, "venderGuarantee");
            return (Criteria) this;
        }

        public Criteria andVenderGuaranteeGreaterThanOrEqualTo(Integer value) {
            addCriterion("vender_guarantee >=", value, "venderGuarantee");
            return (Criteria) this;
        }

        public Criteria andVenderGuaranteeLessThan(Integer value) {
            addCriterion("vender_guarantee <", value, "venderGuarantee");
            return (Criteria) this;
        }

        public Criteria andVenderGuaranteeLessThanOrEqualTo(Integer value) {
            addCriterion("vender_guarantee <=", value, "venderGuarantee");
            return (Criteria) this;
        }

        public Criteria andVenderGuaranteeIn(List<Integer> values) {
            addCriterion("vender_guarantee in", values, "venderGuarantee");
            return (Criteria) this;
        }

        public Criteria andVenderGuaranteeNotIn(List<Integer> values) {
            addCriterion("vender_guarantee not in", values, "venderGuarantee");
            return (Criteria) this;
        }

        public Criteria andVenderGuaranteeBetween(Integer value1, Integer value2) {
            addCriterion("vender_guarantee between", value1, value2, "venderGuarantee");
            return (Criteria) this;
        }

        public Criteria andVenderGuaranteeNotBetween(Integer value1, Integer value2) {
            addCriterion("vender_guarantee not between", value1, value2, "venderGuarantee");
            return (Criteria) this;
        }

        public Criteria andPlatformGuaranteeIsNull() {
            addCriterion("platform_guarantee is null");
            return (Criteria) this;
        }

        public Criteria andPlatformGuaranteeIsNotNull() {
            addCriterion("platform_guarantee is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformGuaranteeEqualTo(Integer value) {
            addCriterion("platform_guarantee =", value, "platformGuarantee");
            return (Criteria) this;
        }

        public Criteria andPlatformGuaranteeNotEqualTo(Integer value) {
            addCriterion("platform_guarantee <>", value, "platformGuarantee");
            return (Criteria) this;
        }

        public Criteria andPlatformGuaranteeGreaterThan(Integer value) {
            addCriterion("platform_guarantee >", value, "platformGuarantee");
            return (Criteria) this;
        }

        public Criteria andPlatformGuaranteeGreaterThanOrEqualTo(Integer value) {
            addCriterion("platform_guarantee >=", value, "platformGuarantee");
            return (Criteria) this;
        }

        public Criteria andPlatformGuaranteeLessThan(Integer value) {
            addCriterion("platform_guarantee <", value, "platformGuarantee");
            return (Criteria) this;
        }

        public Criteria andPlatformGuaranteeLessThanOrEqualTo(Integer value) {
            addCriterion("platform_guarantee <=", value, "platformGuarantee");
            return (Criteria) this;
        }

        public Criteria andPlatformGuaranteeIn(List<Integer> values) {
            addCriterion("platform_guarantee in", values, "platformGuarantee");
            return (Criteria) this;
        }

        public Criteria andPlatformGuaranteeNotIn(List<Integer> values) {
            addCriterion("platform_guarantee not in", values, "platformGuarantee");
            return (Criteria) this;
        }

        public Criteria andPlatformGuaranteeBetween(Integer value1, Integer value2) {
            addCriterion("platform_guarantee between", value1, value2, "platformGuarantee");
            return (Criteria) this;
        }

        public Criteria andPlatformGuaranteeNotBetween(Integer value1, Integer value2) {
            addCriterion("platform_guarantee not between", value1, value2, "platformGuarantee");
            return (Criteria) this;
        }

        public Criteria andOperatorCompIsNull() {
            addCriterion("operator_comp is null");
            return (Criteria) this;
        }

        public Criteria andOperatorCompIsNotNull() {
            addCriterion("operator_comp is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorCompEqualTo(String value) {
            addCriterion("operator_comp =", value, "operatorComp");
            return (Criteria) this;
        }

        public Criteria andOperatorCompNotEqualTo(String value) {
            addCriterion("operator_comp <>", value, "operatorComp");
            return (Criteria) this;
        }

        public Criteria andOperatorCompGreaterThan(String value) {
            addCriterion("operator_comp >", value, "operatorComp");
            return (Criteria) this;
        }

        public Criteria andOperatorCompGreaterThanOrEqualTo(String value) {
            addCriterion("operator_comp >=", value, "operatorComp");
            return (Criteria) this;
        }

        public Criteria andOperatorCompLessThan(String value) {
            addCriterion("operator_comp <", value, "operatorComp");
            return (Criteria) this;
        }

        public Criteria andOperatorCompLessThanOrEqualTo(String value) {
            addCriterion("operator_comp <=", value, "operatorComp");
            return (Criteria) this;
        }

        public Criteria andOperatorCompLike(String value) {
            addCriterion("operator_comp like", value, "operatorComp");
            return (Criteria) this;
        }

        public Criteria andOperatorCompNotLike(String value) {
            addCriterion("operator_comp not like", value, "operatorComp");
            return (Criteria) this;
        }

        public Criteria andOperatorCompIn(List<String> values) {
            addCriterion("operator_comp in", values, "operatorComp");
            return (Criteria) this;
        }

        public Criteria andOperatorCompNotIn(List<String> values) {
            addCriterion("operator_comp not in", values, "operatorComp");
            return (Criteria) this;
        }

        public Criteria andOperatorCompBetween(String value1, String value2) {
            addCriterion("operator_comp between", value1, value2, "operatorComp");
            return (Criteria) this;
        }

        public Criteria andOperatorCompNotBetween(String value1, String value2) {
            addCriterion("operator_comp not between", value1, value2, "operatorComp");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(Integer value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(Integer value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(Integer value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(Integer value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(Integer value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<Integer> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<Integer> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(Integer value1, Integer value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(Integer value1, Integer value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(Integer value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(Integer value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(Integer value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(Integer value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(Integer value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<Integer> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<Integer> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(Integer value1, Integer value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(Integer value1, Integer value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andMaintenanceChannelIdIsNull() {
            addCriterion("maintenance_channel_id is null");
            return (Criteria) this;
        }

        public Criteria andMaintenanceChannelIdIsNotNull() {
            addCriterion("maintenance_channel_id is not null");
            return (Criteria) this;
        }

        public Criteria andMaintenanceChannelIdEqualTo(Integer value) {
            addCriterion("maintenance_channel_id =", value, "maintenanceChannelId");
            return (Criteria) this;
        }

        public Criteria andMaintenanceChannelIdNotEqualTo(Integer value) {
            addCriterion("maintenance_channel_id <>", value, "maintenanceChannelId");
            return (Criteria) this;
        }

        public Criteria andMaintenanceChannelIdGreaterThan(Integer value) {
            addCriterion("maintenance_channel_id >", value, "maintenanceChannelId");
            return (Criteria) this;
        }

        public Criteria andMaintenanceChannelIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("maintenance_channel_id >=", value, "maintenanceChannelId");
            return (Criteria) this;
        }

        public Criteria andMaintenanceChannelIdLessThan(Integer value) {
            addCriterion("maintenance_channel_id <", value, "maintenanceChannelId");
            return (Criteria) this;
        }

        public Criteria andMaintenanceChannelIdLessThanOrEqualTo(Integer value) {
            addCriterion("maintenance_channel_id <=", value, "maintenanceChannelId");
            return (Criteria) this;
        }

        public Criteria andMaintenanceChannelIdIn(List<Integer> values) {
            addCriterion("maintenance_channel_id in", values, "maintenanceChannelId");
            return (Criteria) this;
        }

        public Criteria andMaintenanceChannelIdNotIn(List<Integer> values) {
            addCriterion("maintenance_channel_id not in", values, "maintenanceChannelId");
            return (Criteria) this;
        }

        public Criteria andMaintenanceChannelIdBetween(Integer value1, Integer value2) {
            addCriterion("maintenance_channel_id between", value1, value2, "maintenanceChannelId");
            return (Criteria) this;
        }

        public Criteria andMaintenanceChannelIdNotBetween(Integer value1, Integer value2) {
            addCriterion("maintenance_channel_id not between", value1, value2, "maintenanceChannelId");
            return (Criteria) this;
        }

        public Criteria andSellFlagIsNull() {
            addCriterion("sell_flag is null");
            return (Criteria) this;
        }

        public Criteria andSellFlagIsNotNull() {
            addCriterion("sell_flag is not null");
            return (Criteria) this;
        }

        public Criteria andSellFlagEqualTo(Integer value) {
            addCriterion("sell_flag =", value, "sellFlag");
            return (Criteria) this;
        }

        public Criteria andSellFlagNotEqualTo(Integer value) {
            addCriterion("sell_flag <>", value, "sellFlag");
            return (Criteria) this;
        }

        public Criteria andSellFlagGreaterThan(Integer value) {
            addCriterion("sell_flag >", value, "sellFlag");
            return (Criteria) this;
        }

        public Criteria andSellFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("sell_flag >=", value, "sellFlag");
            return (Criteria) this;
        }

        public Criteria andSellFlagLessThan(Integer value) {
            addCriterion("sell_flag <", value, "sellFlag");
            return (Criteria) this;
        }

        public Criteria andSellFlagLessThanOrEqualTo(Integer value) {
            addCriterion("sell_flag <=", value, "sellFlag");
            return (Criteria) this;
        }

        public Criteria andSellFlagIn(List<Integer> values) {
            addCriterion("sell_flag in", values, "sellFlag");
            return (Criteria) this;
        }

        public Criteria andSellFlagNotIn(List<Integer> values) {
            addCriterion("sell_flag not in", values, "sellFlag");
            return (Criteria) this;
        }

        public Criteria andSellFlagBetween(Integer value1, Integer value2) {
            addCriterion("sell_flag between", value1, value2, "sellFlag");
            return (Criteria) this;
        }

        public Criteria andSellFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("sell_flag not between", value1, value2, "sellFlag");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNull() {
            addCriterion("brand_id is null");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNotNull() {
            addCriterion("brand_id is not null");
            return (Criteria) this;
        }

        public Criteria andBrandIdEqualTo(Integer value) {
            addCriterion("brand_id =", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotEqualTo(Integer value) {
            addCriterion("brand_id <>", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThan(Integer value) {
            addCriterion("brand_id >", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("brand_id >=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThan(Integer value) {
            addCriterion("brand_id <", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThanOrEqualTo(Integer value) {
            addCriterion("brand_id <=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdIn(List<Integer> values) {
            addCriterion("brand_id in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotIn(List<Integer> values) {
            addCriterion("brand_id not in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdBetween(Integer value1, Integer value2) {
            addCriterion("brand_id between", value1, value2, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotBetween(Integer value1, Integer value2) {
            addCriterion("brand_id not between", value1, value2, "brandId");
            return (Criteria) this;
        }

        public Criteria andSpuGoodsIdIsNull() {
            addCriterion("spu_goods_id is null");
            return (Criteria) this;
        }

        public Criteria andSpuGoodsIdIsNotNull() {
            addCriterion("spu_goods_id is not null");
            return (Criteria) this;
        }

        public Criteria andSpuGoodsIdEqualTo(Integer value) {
            addCriterion("spu_goods_id =", value, "spuGoodsId");
            return (Criteria) this;
        }

        public Criteria andSpuGoodsIdNotEqualTo(Integer value) {
            addCriterion("spu_goods_id <>", value, "spuGoodsId");
            return (Criteria) this;
        }

        public Criteria andSpuGoodsIdGreaterThan(Integer value) {
            addCriterion("spu_goods_id >", value, "spuGoodsId");
            return (Criteria) this;
        }

        public Criteria andSpuGoodsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("spu_goods_id >=", value, "spuGoodsId");
            return (Criteria) this;
        }

        public Criteria andSpuGoodsIdLessThan(Integer value) {
            addCriterion("spu_goods_id <", value, "spuGoodsId");
            return (Criteria) this;
        }

        public Criteria andSpuGoodsIdLessThanOrEqualTo(Integer value) {
            addCriterion("spu_goods_id <=", value, "spuGoodsId");
            return (Criteria) this;
        }

        public Criteria andSpuGoodsIdIn(List<Integer> values) {
            addCriterion("spu_goods_id in", values, "spuGoodsId");
            return (Criteria) this;
        }

        public Criteria andSpuGoodsIdNotIn(List<Integer> values) {
            addCriterion("spu_goods_id not in", values, "spuGoodsId");
            return (Criteria) this;
        }

        public Criteria andSpuGoodsIdBetween(Integer value1, Integer value2) {
            addCriterion("spu_goods_id between", value1, value2, "spuGoodsId");
            return (Criteria) this;
        }

        public Criteria andSpuGoodsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("spu_goods_id not between", value1, value2, "spuGoodsId");
            return (Criteria) this;
        }

        public Criteria andOmtFlagIsNull() {
            addCriterion("omt_flag is null");
            return (Criteria) this;
        }

        public Criteria andOmtFlagIsNotNull() {
            addCriterion("omt_flag is not null");
            return (Criteria) this;
        }

        public Criteria andOmtFlagEqualTo(Integer value) {
            addCriterion("omt_flag =", value, "omtFlag");
            return (Criteria) this;
        }

        public Criteria andOmtFlagNotEqualTo(Integer value) {
            addCriterion("omt_flag <>", value, "omtFlag");
            return (Criteria) this;
        }

        public Criteria andOmtFlagGreaterThan(Integer value) {
            addCriterion("omt_flag >", value, "omtFlag");
            return (Criteria) this;
        }

        public Criteria andOmtFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("omt_flag >=", value, "omtFlag");
            return (Criteria) this;
        }

        public Criteria andOmtFlagLessThan(Integer value) {
            addCriterion("omt_flag <", value, "omtFlag");
            return (Criteria) this;
        }

        public Criteria andOmtFlagLessThanOrEqualTo(Integer value) {
            addCriterion("omt_flag <=", value, "omtFlag");
            return (Criteria) this;
        }

        public Criteria andOmtFlagIn(List<Integer> values) {
            addCriterion("omt_flag in", values, "omtFlag");
            return (Criteria) this;
        }

        public Criteria andOmtFlagNotIn(List<Integer> values) {
            addCriterion("omt_flag not in", values, "omtFlag");
            return (Criteria) this;
        }

        public Criteria andOmtFlagBetween(Integer value1, Integer value2) {
            addCriterion("omt_flag between", value1, value2, "omtFlag");
            return (Criteria) this;
        }

        public Criteria andOmtFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("omt_flag not between", value1, value2, "omtFlag");
            return (Criteria) this;
        }

        public Criteria andSpecialMaterialFlagIsNull() {
            addCriterion("special_material_flag is null");
            return (Criteria) this;
        }

        public Criteria andSpecialMaterialFlagIsNotNull() {
            addCriterion("special_material_flag is not null");
            return (Criteria) this;
        }

        public Criteria andSpecialMaterialFlagEqualTo(Integer value) {
            addCriterion("special_material_flag =", value, "specialMaterialFlag");
            return (Criteria) this;
        }

        public Criteria andSpecialMaterialFlagNotEqualTo(Integer value) {
            addCriterion("special_material_flag <>", value, "specialMaterialFlag");
            return (Criteria) this;
        }

        public Criteria andSpecialMaterialFlagGreaterThan(Integer value) {
            addCriterion("special_material_flag >", value, "specialMaterialFlag");
            return (Criteria) this;
        }

        public Criteria andSpecialMaterialFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("special_material_flag >=", value, "specialMaterialFlag");
            return (Criteria) this;
        }

        public Criteria andSpecialMaterialFlagLessThan(Integer value) {
            addCriterion("special_material_flag <", value, "specialMaterialFlag");
            return (Criteria) this;
        }

        public Criteria andSpecialMaterialFlagLessThanOrEqualTo(Integer value) {
            addCriterion("special_material_flag <=", value, "specialMaterialFlag");
            return (Criteria) this;
        }

        public Criteria andSpecialMaterialFlagIn(List<Integer> values) {
            addCriterion("special_material_flag in", values, "specialMaterialFlag");
            return (Criteria) this;
        }

        public Criteria andSpecialMaterialFlagNotIn(List<Integer> values) {
            addCriterion("special_material_flag not in", values, "specialMaterialFlag");
            return (Criteria) this;
        }

        public Criteria andSpecialMaterialFlagBetween(Integer value1, Integer value2) {
            addCriterion("special_material_flag between", value1, value2, "specialMaterialFlag");
            return (Criteria) this;
        }

        public Criteria andSpecialMaterialFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("special_material_flag not between", value1, value2, "specialMaterialFlag");
            return (Criteria) this;
        }

        public Criteria andScreateTimeIsNull() {
            addCriterion("screate_time is null");
            return (Criteria) this;
        }

        public Criteria andScreateTimeIsNotNull() {
            addCriterion("screate_time is not null");
            return (Criteria) this;
        }

        public Criteria andScreateTimeEqualTo(Date value) {
            addCriterion("screate_time =", value, "screateTime");
            return (Criteria) this;
        }

        public Criteria andScreateTimeNotEqualTo(Date value) {
            addCriterion("screate_time <>", value, "screateTime");
            return (Criteria) this;
        }

        public Criteria andScreateTimeGreaterThan(Date value) {
            addCriterion("screate_time >", value, "screateTime");
            return (Criteria) this;
        }

        public Criteria andScreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("screate_time >=", value, "screateTime");
            return (Criteria) this;
        }

        public Criteria andScreateTimeLessThan(Date value) {
            addCriterion("screate_time <", value, "screateTime");
            return (Criteria) this;
        }

        public Criteria andScreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("screate_time <=", value, "screateTime");
            return (Criteria) this;
        }

        public Criteria andScreateTimeIn(List<Date> values) {
            addCriterion("screate_time in", values, "screateTime");
            return (Criteria) this;
        }

        public Criteria andScreateTimeNotIn(List<Date> values) {
            addCriterion("screate_time not in", values, "screateTime");
            return (Criteria) this;
        }

        public Criteria andScreateTimeBetween(Date value1, Date value2) {
            addCriterion("screate_time between", value1, value2, "screateTime");
            return (Criteria) this;
        }

        public Criteria andScreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("screate_time not between", value1, value2, "screateTime");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeIsNull() {
            addCriterion("supdate_time is null");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeIsNotNull() {
            addCriterion("supdate_time is not null");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeEqualTo(Date value) {
            addCriterion("supdate_time =", value, "supdateTime");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeNotEqualTo(Date value) {
            addCriterion("supdate_time <>", value, "supdateTime");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeGreaterThan(Date value) {
            addCriterion("supdate_time >", value, "supdateTime");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("supdate_time >=", value, "supdateTime");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeLessThan(Date value) {
            addCriterion("supdate_time <", value, "supdateTime");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("supdate_time <=", value, "supdateTime");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeIn(List<Date> values) {
            addCriterion("supdate_time in", values, "supdateTime");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeNotIn(List<Date> values) {
            addCriterion("supdate_time not in", values, "supdateTime");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeBetween(Date value1, Date value2) {
            addCriterion("supdate_time between", value1, value2, "supdateTime");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("supdate_time not between", value1, value2, "supdateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table material_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table material_info
     *
     * @mbg.generated
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}