package com.hy.repository.po;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SvcServiceItemPOExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table svc_service_item
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table svc_service_item
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table svc_service_item
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table svc_service_item
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svc_service_item
     *
     * @mbg.generated
     */
    public SvcServiceItemPOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svc_service_item
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svc_service_item
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svc_service_item
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svc_service_item
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svc_service_item
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svc_service_item
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svc_service_item
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svc_service_item
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svc_service_item
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table svc_service_item
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table svc_service_item
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andServiceItemIdIsNull() {
            addCriterion("service_item_id is null");
            return (Criteria) this;
        }

        public Criteria andServiceItemIdIsNotNull() {
            addCriterion("service_item_id is not null");
            return (Criteria) this;
        }

        public Criteria andServiceItemIdEqualTo(Integer value) {
            addCriterion("service_item_id =", value, "serviceItemId");
            return (Criteria) this;
        }

        public Criteria andServiceItemIdNotEqualTo(Integer value) {
            addCriterion("service_item_id <>", value, "serviceItemId");
            return (Criteria) this;
        }

        public Criteria andServiceItemIdGreaterThan(Integer value) {
            addCriterion("service_item_id >", value, "serviceItemId");
            return (Criteria) this;
        }

        public Criteria andServiceItemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("service_item_id >=", value, "serviceItemId");
            return (Criteria) this;
        }

        public Criteria andServiceItemIdLessThan(Integer value) {
            addCriterion("service_item_id <", value, "serviceItemId");
            return (Criteria) this;
        }

        public Criteria andServiceItemIdLessThanOrEqualTo(Integer value) {
            addCriterion("service_item_id <=", value, "serviceItemId");
            return (Criteria) this;
        }

        public Criteria andServiceItemIdIn(List<Integer> values) {
            addCriterion("service_item_id in", values, "serviceItemId");
            return (Criteria) this;
        }

        public Criteria andServiceItemIdNotIn(List<Integer> values) {
            addCriterion("service_item_id not in", values, "serviceItemId");
            return (Criteria) this;
        }

        public Criteria andServiceItemIdBetween(Integer value1, Integer value2) {
            addCriterion("service_item_id between", value1, value2, "serviceItemId");
            return (Criteria) this;
        }

        public Criteria andServiceItemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("service_item_id not between", value1, value2, "serviceItemId");
            return (Criteria) this;
        }

        public Criteria andServiceClassIdIsNull() {
            addCriterion("service_class_id is null");
            return (Criteria) this;
        }

        public Criteria andServiceClassIdIsNotNull() {
            addCriterion("service_class_id is not null");
            return (Criteria) this;
        }

        public Criteria andServiceClassIdEqualTo(Integer value) {
            addCriterion("service_class_id =", value, "serviceClassId");
            return (Criteria) this;
        }

        public Criteria andServiceClassIdNotEqualTo(Integer value) {
            addCriterion("service_class_id <>", value, "serviceClassId");
            return (Criteria) this;
        }

        public Criteria andServiceClassIdGreaterThan(Integer value) {
            addCriterion("service_class_id >", value, "serviceClassId");
            return (Criteria) this;
        }

        public Criteria andServiceClassIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("service_class_id >=", value, "serviceClassId");
            return (Criteria) this;
        }

        public Criteria andServiceClassIdLessThan(Integer value) {
            addCriterion("service_class_id <", value, "serviceClassId");
            return (Criteria) this;
        }

        public Criteria andServiceClassIdLessThanOrEqualTo(Integer value) {
            addCriterion("service_class_id <=", value, "serviceClassId");
            return (Criteria) this;
        }

        public Criteria andServiceClassIdIn(List<Integer> values) {
            addCriterion("service_class_id in", values, "serviceClassId");
            return (Criteria) this;
        }

        public Criteria andServiceClassIdNotIn(List<Integer> values) {
            addCriterion("service_class_id not in", values, "serviceClassId");
            return (Criteria) this;
        }

        public Criteria andServiceClassIdBetween(Integer value1, Integer value2) {
            addCriterion("service_class_id between", value1, value2, "serviceClassId");
            return (Criteria) this;
        }

        public Criteria andServiceClassIdNotBetween(Integer value1, Integer value2) {
            addCriterion("service_class_id not between", value1, value2, "serviceClassId");
            return (Criteria) this;
        }

        public Criteria andBigClassIdIsNull() {
            addCriterion("big_class_id is null");
            return (Criteria) this;
        }

        public Criteria andBigClassIdIsNotNull() {
            addCriterion("big_class_id is not null");
            return (Criteria) this;
        }

        public Criteria andBigClassIdEqualTo(Integer value) {
            addCriterion("big_class_id =", value, "bigClassId");
            return (Criteria) this;
        }

        public Criteria andBigClassIdNotEqualTo(Integer value) {
            addCriterion("big_class_id <>", value, "bigClassId");
            return (Criteria) this;
        }

        public Criteria andBigClassIdGreaterThan(Integer value) {
            addCriterion("big_class_id >", value, "bigClassId");
            return (Criteria) this;
        }

        public Criteria andBigClassIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("big_class_id >=", value, "bigClassId");
            return (Criteria) this;
        }

        public Criteria andBigClassIdLessThan(Integer value) {
            addCriterion("big_class_id <", value, "bigClassId");
            return (Criteria) this;
        }

        public Criteria andBigClassIdLessThanOrEqualTo(Integer value) {
            addCriterion("big_class_id <=", value, "bigClassId");
            return (Criteria) this;
        }

        public Criteria andBigClassIdIn(List<Integer> values) {
            addCriterion("big_class_id in", values, "bigClassId");
            return (Criteria) this;
        }

        public Criteria andBigClassIdNotIn(List<Integer> values) {
            addCriterion("big_class_id not in", values, "bigClassId");
            return (Criteria) this;
        }

        public Criteria andBigClassIdBetween(Integer value1, Integer value2) {
            addCriterion("big_class_id between", value1, value2, "bigClassId");
            return (Criteria) this;
        }

        public Criteria andBigClassIdNotBetween(Integer value1, Integer value2) {
            addCriterion("big_class_id not between", value1, value2, "bigClassId");
            return (Criteria) this;
        }

        public Criteria andServiceItemNameIsNull() {
            addCriterion("service_item_name is null");
            return (Criteria) this;
        }

        public Criteria andServiceItemNameIsNotNull() {
            addCriterion("service_item_name is not null");
            return (Criteria) this;
        }

        public Criteria andServiceItemNameEqualTo(String value) {
            addCriterion("service_item_name =", value, "serviceItemName");
            return (Criteria) this;
        }

        public Criteria andServiceItemNameNotEqualTo(String value) {
            addCriterion("service_item_name <>", value, "serviceItemName");
            return (Criteria) this;
        }

        public Criteria andServiceItemNameGreaterThan(String value) {
            addCriterion("service_item_name >", value, "serviceItemName");
            return (Criteria) this;
        }

        public Criteria andServiceItemNameGreaterThanOrEqualTo(String value) {
            addCriterion("service_item_name >=", value, "serviceItemName");
            return (Criteria) this;
        }

        public Criteria andServiceItemNameLessThan(String value) {
            addCriterion("service_item_name <", value, "serviceItemName");
            return (Criteria) this;
        }

        public Criteria andServiceItemNameLessThanOrEqualTo(String value) {
            addCriterion("service_item_name <=", value, "serviceItemName");
            return (Criteria) this;
        }

        public Criteria andServiceItemNameLike(String value) {
            addCriterion("service_item_name like", value, "serviceItemName");
            return (Criteria) this;
        }

        public Criteria andServiceItemNameNotLike(String value) {
            addCriterion("service_item_name not like", value, "serviceItemName");
            return (Criteria) this;
        }

        public Criteria andServiceItemNameIn(List<String> values) {
            addCriterion("service_item_name in", values, "serviceItemName");
            return (Criteria) this;
        }

        public Criteria andServiceItemNameNotIn(List<String> values) {
            addCriterion("service_item_name not in", values, "serviceItemName");
            return (Criteria) this;
        }

        public Criteria andServiceItemNameBetween(String value1, String value2) {
            addCriterion("service_item_name between", value1, value2, "serviceItemName");
            return (Criteria) this;
        }

        public Criteria andServiceItemNameNotBetween(String value1, String value2) {
            addCriterion("service_item_name not between", value1, value2, "serviceItemName");
            return (Criteria) this;
        }

        public Criteria andBaseDataVersionIsNull() {
            addCriterion("base_data_version is null");
            return (Criteria) this;
        }

        public Criteria andBaseDataVersionIsNotNull() {
            addCriterion("base_data_version is not null");
            return (Criteria) this;
        }

        public Criteria andBaseDataVersionEqualTo(Integer value) {
            addCriterion("base_data_version =", value, "baseDataVersion");
            return (Criteria) this;
        }

        public Criteria andBaseDataVersionNotEqualTo(Integer value) {
            addCriterion("base_data_version <>", value, "baseDataVersion");
            return (Criteria) this;
        }

        public Criteria andBaseDataVersionGreaterThan(Integer value) {
            addCriterion("base_data_version >", value, "baseDataVersion");
            return (Criteria) this;
        }

        public Criteria andBaseDataVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("base_data_version >=", value, "baseDataVersion");
            return (Criteria) this;
        }

        public Criteria andBaseDataVersionLessThan(Integer value) {
            addCriterion("base_data_version <", value, "baseDataVersion");
            return (Criteria) this;
        }

        public Criteria andBaseDataVersionLessThanOrEqualTo(Integer value) {
            addCriterion("base_data_version <=", value, "baseDataVersion");
            return (Criteria) this;
        }

        public Criteria andBaseDataVersionIn(List<Integer> values) {
            addCriterion("base_data_version in", values, "baseDataVersion");
            return (Criteria) this;
        }

        public Criteria andBaseDataVersionNotIn(List<Integer> values) {
            addCriterion("base_data_version not in", values, "baseDataVersion");
            return (Criteria) this;
        }

        public Criteria andBaseDataVersionBetween(Integer value1, Integer value2) {
            addCriterion("base_data_version between", value1, value2, "baseDataVersion");
            return (Criteria) this;
        }

        public Criteria andBaseDataVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("base_data_version not between", value1, value2, "baseDataVersion");
            return (Criteria) this;
        }

        public Criteria andQualityGuaranteeIsNull() {
            addCriterion("quality_guarantee is null");
            return (Criteria) this;
        }

        public Criteria andQualityGuaranteeIsNotNull() {
            addCriterion("quality_guarantee is not null");
            return (Criteria) this;
        }

        public Criteria andQualityGuaranteeEqualTo(Integer value) {
            addCriterion("quality_guarantee =", value, "qualityGuarantee");
            return (Criteria) this;
        }

        public Criteria andQualityGuaranteeNotEqualTo(Integer value) {
            addCriterion("quality_guarantee <>", value, "qualityGuarantee");
            return (Criteria) this;
        }

        public Criteria andQualityGuaranteeGreaterThan(Integer value) {
            addCriterion("quality_guarantee >", value, "qualityGuarantee");
            return (Criteria) this;
        }

        public Criteria andQualityGuaranteeGreaterThanOrEqualTo(Integer value) {
            addCriterion("quality_guarantee >=", value, "qualityGuarantee");
            return (Criteria) this;
        }

        public Criteria andQualityGuaranteeLessThan(Integer value) {
            addCriterion("quality_guarantee <", value, "qualityGuarantee");
            return (Criteria) this;
        }

        public Criteria andQualityGuaranteeLessThanOrEqualTo(Integer value) {
            addCriterion("quality_guarantee <=", value, "qualityGuarantee");
            return (Criteria) this;
        }

        public Criteria andQualityGuaranteeIn(List<Integer> values) {
            addCriterion("quality_guarantee in", values, "qualityGuarantee");
            return (Criteria) this;
        }

        public Criteria andQualityGuaranteeNotIn(List<Integer> values) {
            addCriterion("quality_guarantee not in", values, "qualityGuarantee");
            return (Criteria) this;
        }

        public Criteria andQualityGuaranteeBetween(Integer value1, Integer value2) {
            addCriterion("quality_guarantee between", value1, value2, "qualityGuarantee");
            return (Criteria) this;
        }

        public Criteria andQualityGuaranteeNotBetween(Integer value1, Integer value2) {
            addCriterion("quality_guarantee not between", value1, value2, "qualityGuarantee");
            return (Criteria) this;
        }

        public Criteria andChargeUnitIsNull() {
            addCriterion("charge_unit is null");
            return (Criteria) this;
        }

        public Criteria andChargeUnitIsNotNull() {
            addCriterion("charge_unit is not null");
            return (Criteria) this;
        }

        public Criteria andChargeUnitEqualTo(String value) {
            addCriterion("charge_unit =", value, "chargeUnit");
            return (Criteria) this;
        }

        public Criteria andChargeUnitNotEqualTo(String value) {
            addCriterion("charge_unit <>", value, "chargeUnit");
            return (Criteria) this;
        }

        public Criteria andChargeUnitGreaterThan(String value) {
            addCriterion("charge_unit >", value, "chargeUnit");
            return (Criteria) this;
        }

        public Criteria andChargeUnitGreaterThanOrEqualTo(String value) {
            addCriterion("charge_unit >=", value, "chargeUnit");
            return (Criteria) this;
        }

        public Criteria andChargeUnitLessThan(String value) {
            addCriterion("charge_unit <", value, "chargeUnit");
            return (Criteria) this;
        }

        public Criteria andChargeUnitLessThanOrEqualTo(String value) {
            addCriterion("charge_unit <=", value, "chargeUnit");
            return (Criteria) this;
        }

        public Criteria andChargeUnitLike(String value) {
            addCriterion("charge_unit like", value, "chargeUnit");
            return (Criteria) this;
        }

        public Criteria andChargeUnitNotLike(String value) {
            addCriterion("charge_unit not like", value, "chargeUnit");
            return (Criteria) this;
        }

        public Criteria andChargeUnitIn(List<String> values) {
            addCriterion("charge_unit in", values, "chargeUnit");
            return (Criteria) this;
        }

        public Criteria andChargeUnitNotIn(List<String> values) {
            addCriterion("charge_unit not in", values, "chargeUnit");
            return (Criteria) this;
        }

        public Criteria andChargeUnitBetween(String value1, String value2) {
            addCriterion("charge_unit between", value1, value2, "chargeUnit");
            return (Criteria) this;
        }

        public Criteria andChargeUnitNotBetween(String value1, String value2) {
            addCriterion("charge_unit not between", value1, value2, "chargeUnit");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(Integer value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(Integer value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(Integer value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(Integer value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(Integer value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<Integer> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<Integer> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(Integer value1, Integer value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(Integer value1, Integer value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(Integer value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(Integer value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(Integer value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(Integer value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(Integer value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<Integer> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<Integer> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(Integer value1, Integer value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(Integer value1, Integer value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andOffFlagIsNull() {
            addCriterion("off_flag is null");
            return (Criteria) this;
        }

        public Criteria andOffFlagIsNotNull() {
            addCriterion("off_flag is not null");
            return (Criteria) this;
        }

        public Criteria andOffFlagEqualTo(Integer value) {
            addCriterion("off_flag =", value, "offFlag");
            return (Criteria) this;
        }

        public Criteria andOffFlagNotEqualTo(Integer value) {
            addCriterion("off_flag <>", value, "offFlag");
            return (Criteria) this;
        }

        public Criteria andOffFlagGreaterThan(Integer value) {
            addCriterion("off_flag >", value, "offFlag");
            return (Criteria) this;
        }

        public Criteria andOffFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("off_flag >=", value, "offFlag");
            return (Criteria) this;
        }

        public Criteria andOffFlagLessThan(Integer value) {
            addCriterion("off_flag <", value, "offFlag");
            return (Criteria) this;
        }

        public Criteria andOffFlagLessThanOrEqualTo(Integer value) {
            addCriterion("off_flag <=", value, "offFlag");
            return (Criteria) this;
        }

        public Criteria andOffFlagIn(List<Integer> values) {
            addCriterion("off_flag in", values, "offFlag");
            return (Criteria) this;
        }

        public Criteria andOffFlagNotIn(List<Integer> values) {
            addCriterion("off_flag not in", values, "offFlag");
            return (Criteria) this;
        }

        public Criteria andOffFlagBetween(Integer value1, Integer value2) {
            addCriterion("off_flag between", value1, value2, "offFlag");
            return (Criteria) this;
        }

        public Criteria andOffFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("off_flag not between", value1, value2, "offFlag");
            return (Criteria) this;
        }

        public Criteria andIsmallFlagIsNull() {
            addCriterion("ismall_flag is null");
            return (Criteria) this;
        }

        public Criteria andIsmallFlagIsNotNull() {
            addCriterion("ismall_flag is not null");
            return (Criteria) this;
        }

        public Criteria andIsmallFlagEqualTo(Integer value) {
            addCriterion("ismall_flag =", value, "ismallFlag");
            return (Criteria) this;
        }

        public Criteria andIsmallFlagNotEqualTo(Integer value) {
            addCriterion("ismall_flag <>", value, "ismallFlag");
            return (Criteria) this;
        }

        public Criteria andIsmallFlagGreaterThan(Integer value) {
            addCriterion("ismall_flag >", value, "ismallFlag");
            return (Criteria) this;
        }

        public Criteria andIsmallFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("ismall_flag >=", value, "ismallFlag");
            return (Criteria) this;
        }

        public Criteria andIsmallFlagLessThan(Integer value) {
            addCriterion("ismall_flag <", value, "ismallFlag");
            return (Criteria) this;
        }

        public Criteria andIsmallFlagLessThanOrEqualTo(Integer value) {
            addCriterion("ismall_flag <=", value, "ismallFlag");
            return (Criteria) this;
        }

        public Criteria andIsmallFlagIn(List<Integer> values) {
            addCriterion("ismall_flag in", values, "ismallFlag");
            return (Criteria) this;
        }

        public Criteria andIsmallFlagNotIn(List<Integer> values) {
            addCriterion("ismall_flag not in", values, "ismallFlag");
            return (Criteria) this;
        }

        public Criteria andIsmallFlagBetween(Integer value1, Integer value2) {
            addCriterion("ismall_flag between", value1, value2, "ismallFlag");
            return (Criteria) this;
        }

        public Criteria andIsmallFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("ismall_flag not between", value1, value2, "ismallFlag");
            return (Criteria) this;
        }

        public Criteria andScreateTimeIsNull() {
            addCriterion("screate_time is null");
            return (Criteria) this;
        }

        public Criteria andScreateTimeIsNotNull() {
            addCriterion("screate_time is not null");
            return (Criteria) this;
        }

        public Criteria andScreateTimeEqualTo(Date value) {
            addCriterion("screate_time =", value, "screateTime");
            return (Criteria) this;
        }

        public Criteria andScreateTimeNotEqualTo(Date value) {
            addCriterion("screate_time <>", value, "screateTime");
            return (Criteria) this;
        }

        public Criteria andScreateTimeGreaterThan(Date value) {
            addCriterion("screate_time >", value, "screateTime");
            return (Criteria) this;
        }

        public Criteria andScreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("screate_time >=", value, "screateTime");
            return (Criteria) this;
        }

        public Criteria andScreateTimeLessThan(Date value) {
            addCriterion("screate_time <", value, "screateTime");
            return (Criteria) this;
        }

        public Criteria andScreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("screate_time <=", value, "screateTime");
            return (Criteria) this;
        }

        public Criteria andScreateTimeIn(List<Date> values) {
            addCriterion("screate_time in", values, "screateTime");
            return (Criteria) this;
        }

        public Criteria andScreateTimeNotIn(List<Date> values) {
            addCriterion("screate_time not in", values, "screateTime");
            return (Criteria) this;
        }

        public Criteria andScreateTimeBetween(Date value1, Date value2) {
            addCriterion("screate_time between", value1, value2, "screateTime");
            return (Criteria) this;
        }

        public Criteria andScreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("screate_time not between", value1, value2, "screateTime");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeIsNull() {
            addCriterion("supdate_time is null");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeIsNotNull() {
            addCriterion("supdate_time is not null");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeEqualTo(Date value) {
            addCriterion("supdate_time =", value, "supdateTime");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeNotEqualTo(Date value) {
            addCriterion("supdate_time <>", value, "supdateTime");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeGreaterThan(Date value) {
            addCriterion("supdate_time >", value, "supdateTime");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("supdate_time >=", value, "supdateTime");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeLessThan(Date value) {
            addCriterion("supdate_time <", value, "supdateTime");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("supdate_time <=", value, "supdateTime");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeIn(List<Date> values) {
            addCriterion("supdate_time in", values, "supdateTime");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeNotIn(List<Date> values) {
            addCriterion("supdate_time not in", values, "supdateTime");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeBetween(Date value1, Date value2) {
            addCriterion("supdate_time between", value1, value2, "supdateTime");
            return (Criteria) this;
        }

        public Criteria andSupdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("supdate_time not between", value1, value2, "supdateTime");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("del_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("del_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Integer value) {
            addCriterion("del_flag =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Integer value) {
            addCriterion("del_flag <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Integer value) {
            addCriterion("del_flag >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("del_flag >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Integer value) {
            addCriterion("del_flag <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Integer value) {
            addCriterion("del_flag <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Integer> values) {
            addCriterion("del_flag in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Integer> values) {
            addCriterion("del_flag not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Integer value1, Integer value2) {
            addCriterion("del_flag between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("del_flag not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andNeedPhotoFlagIsNull() {
            addCriterion("need_photo_flag is null");
            return (Criteria) this;
        }

        public Criteria andNeedPhotoFlagIsNotNull() {
            addCriterion("need_photo_flag is not null");
            return (Criteria) this;
        }

        public Criteria andNeedPhotoFlagEqualTo(Integer value) {
            addCriterion("need_photo_flag =", value, "needPhotoFlag");
            return (Criteria) this;
        }

        public Criteria andNeedPhotoFlagNotEqualTo(Integer value) {
            addCriterion("need_photo_flag <>", value, "needPhotoFlag");
            return (Criteria) this;
        }

        public Criteria andNeedPhotoFlagGreaterThan(Integer value) {
            addCriterion("need_photo_flag >", value, "needPhotoFlag");
            return (Criteria) this;
        }

        public Criteria andNeedPhotoFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("need_photo_flag >=", value, "needPhotoFlag");
            return (Criteria) this;
        }

        public Criteria andNeedPhotoFlagLessThan(Integer value) {
            addCriterion("need_photo_flag <", value, "needPhotoFlag");
            return (Criteria) this;
        }

        public Criteria andNeedPhotoFlagLessThanOrEqualTo(Integer value) {
            addCriterion("need_photo_flag <=", value, "needPhotoFlag");
            return (Criteria) this;
        }

        public Criteria andNeedPhotoFlagIn(List<Integer> values) {
            addCriterion("need_photo_flag in", values, "needPhotoFlag");
            return (Criteria) this;
        }

        public Criteria andNeedPhotoFlagNotIn(List<Integer> values) {
            addCriterion("need_photo_flag not in", values, "needPhotoFlag");
            return (Criteria) this;
        }

        public Criteria andNeedPhotoFlagBetween(Integer value1, Integer value2) {
            addCriterion("need_photo_flag between", value1, value2, "needPhotoFlag");
            return (Criteria) this;
        }

        public Criteria andNeedPhotoFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("need_photo_flag not between", value1, value2, "needPhotoFlag");
            return (Criteria) this;
        }

        public Criteria andNeedReasonResultFlagIsNull() {
            addCriterion("need_reason_result_flag is null");
            return (Criteria) this;
        }

        public Criteria andNeedReasonResultFlagIsNotNull() {
            addCriterion("need_reason_result_flag is not null");
            return (Criteria) this;
        }

        public Criteria andNeedReasonResultFlagEqualTo(Integer value) {
            addCriterion("need_reason_result_flag =", value, "needReasonResultFlag");
            return (Criteria) this;
        }

        public Criteria andNeedReasonResultFlagNotEqualTo(Integer value) {
            addCriterion("need_reason_result_flag <>", value, "needReasonResultFlag");
            return (Criteria) this;
        }

        public Criteria andNeedReasonResultFlagGreaterThan(Integer value) {
            addCriterion("need_reason_result_flag >", value, "needReasonResultFlag");
            return (Criteria) this;
        }

        public Criteria andNeedReasonResultFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("need_reason_result_flag >=", value, "needReasonResultFlag");
            return (Criteria) this;
        }

        public Criteria andNeedReasonResultFlagLessThan(Integer value) {
            addCriterion("need_reason_result_flag <", value, "needReasonResultFlag");
            return (Criteria) this;
        }

        public Criteria andNeedReasonResultFlagLessThanOrEqualTo(Integer value) {
            addCriterion("need_reason_result_flag <=", value, "needReasonResultFlag");
            return (Criteria) this;
        }

        public Criteria andNeedReasonResultFlagIn(List<Integer> values) {
            addCriterion("need_reason_result_flag in", values, "needReasonResultFlag");
            return (Criteria) this;
        }

        public Criteria andNeedReasonResultFlagNotIn(List<Integer> values) {
            addCriterion("need_reason_result_flag not in", values, "needReasonResultFlag");
            return (Criteria) this;
        }

        public Criteria andNeedReasonResultFlagBetween(Integer value1, Integer value2) {
            addCriterion("need_reason_result_flag between", value1, value2, "needReasonResultFlag");
            return (Criteria) this;
        }

        public Criteria andNeedReasonResultFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("need_reason_result_flag not between", value1, value2, "needReasonResultFlag");
            return (Criteria) this;
        }

        public Criteria andOrderMaxItemNumIsNull() {
            addCriterion("order_max_item_num is null");
            return (Criteria) this;
        }

        public Criteria andOrderMaxItemNumIsNotNull() {
            addCriterion("order_max_item_num is not null");
            return (Criteria) this;
        }

        public Criteria andOrderMaxItemNumEqualTo(Integer value) {
            addCriterion("order_max_item_num =", value, "orderMaxItemNum");
            return (Criteria) this;
        }

        public Criteria andOrderMaxItemNumNotEqualTo(Integer value) {
            addCriterion("order_max_item_num <>", value, "orderMaxItemNum");
            return (Criteria) this;
        }

        public Criteria andOrderMaxItemNumGreaterThan(Integer value) {
            addCriterion("order_max_item_num >", value, "orderMaxItemNum");
            return (Criteria) this;
        }

        public Criteria andOrderMaxItemNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_max_item_num >=", value, "orderMaxItemNum");
            return (Criteria) this;
        }

        public Criteria andOrderMaxItemNumLessThan(Integer value) {
            addCriterion("order_max_item_num <", value, "orderMaxItemNum");
            return (Criteria) this;
        }

        public Criteria andOrderMaxItemNumLessThanOrEqualTo(Integer value) {
            addCriterion("order_max_item_num <=", value, "orderMaxItemNum");
            return (Criteria) this;
        }

        public Criteria andOrderMaxItemNumIn(List<Integer> values) {
            addCriterion("order_max_item_num in", values, "orderMaxItemNum");
            return (Criteria) this;
        }

        public Criteria andOrderMaxItemNumNotIn(List<Integer> values) {
            addCriterion("order_max_item_num not in", values, "orderMaxItemNum");
            return (Criteria) this;
        }

        public Criteria andOrderMaxItemNumBetween(Integer value1, Integer value2) {
            addCriterion("order_max_item_num between", value1, value2, "orderMaxItemNum");
            return (Criteria) this;
        }

        public Criteria andOrderMaxItemNumNotBetween(Integer value1, Integer value2) {
            addCriterion("order_max_item_num not between", value1, value2, "orderMaxItemNum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table svc_service_item
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table svc_service_item
     *
     * @mbg.generated
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}